module.exports = {
  name: "Gandalf",
  creatureType: "humanoid",
  race: "human",
  classe: "wizard",
  charStatus: [10, 11, 12, 18, 13, 8],
  level: 1,
  healthMax: 10,
  gold: 10,
  equipment: {
    head: "empty",
    back: "empty",
    torso: "empty",
    waist: "empty",
    legs: "empty",
    feet: "empty",
    hands: "empty",
    fingers: ["empty"],
    neck: "empty",
    mainhand: "staff",
    offhand: "empty",
    misc: ["empty"],
  },
  inventory: {
    equipment: [],
    materials: [],
    consumables: ["scroll of fireball"],
    misc: [],
  },
  spells: {
    cantrip: ["firebolt"],
    "1st level": ["magic missile"],
    "2nd level": [],
    "3rd level": [],
    "4th level": [],
    "5th level": [],
    "6th level": [],
    "7th level": [],
    "8th level": [],
    "9th level": [],
  },
};
